services:
  domiming_hub_mongodb:
    image: 'mongo:latest'
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_DATABASE=domining_hub
      - MONGO_INITDB_ROOT_PASSWORD=hola12345
      - MONGO_INITDB_ROOT_USERNAME=root
    restart: always